### PR TITLE
Game Api and UI

### PR DESCRIPTION
**Pull request by ykrueng**
Sorry for the big fat PR. Should have put it on smaller chunks.

- add API calls for the game
- wire up API to display the game map
- wire up navigation to move the player on the map
- add styling

Note: 
- this PR needs the Backend database and APIs to be updated first.
- if you want to run the branch locally, pull the lastest server code, run the `create-world` once again before running this branch.

### CODE REVIEW

**Comment by bcuz** [comment]
@ykrueng did you accidentally add the dependencies here with npm instead of yarn?

**Comment by ykrueng** [comment]
> @ykrueng did you accidentally add the dependencies here with npm instead of yarn?

I don't use `npm` that much, but I cannot be 100% sure.

**Comment by bcuz** [comment]
Awesome! One weirdness I noticed was when a new user registers in an incognito window the map wont show up until the page is refreshed. Not a super big deal. You can merge whenever!

**Comment by ykrueng** [comment]
I will take a look at the map loading issue when I get a chance. For now, I am going to just merge this PR so that others can start helping with styling and stuff.

**Pull request merged**
